blank_issues_enabled: false
contact_links:
  - name: Eclipse Matrix Communication Channels
    url: https://chat.eclipse.org/#/room/#tools.tractus-x:matrix.eclipse.org
    about: Committer Channel from Eclipse


